### ISSUE TITLE
/shorten endpoint not working

### ISSUE THREAD

**Issue by anju-infracloud** [ommore1523/TinyUrl#1]
Getting below error:
![image](https://github.com/ommore1523/TinyUrl/assets/64465822/1afdffd2-0922-453c-ad32-cbe96df8fe66)

**Comment by anju-infracloud** [comment]
I am still getting this issue.

**Comment by anju-infracloud** [comment]
Using below commands to reproduce this:
1. `docker compose up -d`
2. 
```
curl --location 'http://localhost:5000/shorten' \
--header 'Content-Type: application/json' \
--data '{
    "url": "https://google.com"
}'
```

**Comment by ommore1523** [comment]
Hello Please check now , I am getting result and tested on another machine as well,

The issue was regarding your paramater passing , you are passing as json and in code handled as form ,

now this is corrected

**Comment by ommore1523** [comment]
Hello Hiring team,

Please check the status now, the issue was your request was sending
parameters as json and  was handled in code as form,
now it's been resolved, and tested with another machine.

Thank you
Omkar More
